default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: depot_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: depot_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: depot_production
  username: root
  password:
  socket: /tmp/mysql.sock
